[default]
application_name="Neuromorphic Sprint API"
application_description="Faculty Project - Neuromorphic Computing and Supercomputers"

default_log_level="INFO"
default_access_log="True"

request_ssl_verify="True"
request_default_user_agent="neuromorphic-sprint-three"

thingspeak_api_url="https://api.thingspeak.com"

[test]

[qa]

[prod]

default_access_log="False"
sentry_dsn=""
